### ISSUE TITLE
Support for dual battery ThinkPads

### ISSUE THREAD

**Issue by Tarballwalf** [atul-g/plasma-power-monitor#2] opened 2022-02-27 09:53 UTC
Currently, on my T560, it doesn't show the wattage at all. Not sure if it's because of the dual batteries or the fact that the power consumption is under `/sys/class/power_supply/BATx/power_now`

**Comment by martinalex000** [comment] 2022-03-18 09:34
On my T460s the widget works perfectly fine if the laptop is running on the first battery. When switching to the second battery, the indicator still checks the first battery and reports 0.0 W. It would be great if the power consumption on all available batteries could be summed up before displaying.
And thanks a lot for this super simple, but very helpful widget!

**Comment by j4nm4c** [comment] 2022-07-04 15:40
Solved this on my ThinkPad by editing the main.qml file to display the sum of BAT0 and BAT1. Not the best way but... it just works. (you can easily change the BATx numbers if it differs for you).
Edited file: [main.zip](https://github.com/atul-g/plasma-power-monitor/files/9040707/main.zip)
It should be enough to replace the main.qml file in ~/.local/share/plasma/plasmoids/org.kde.powerMonitor/contents/ui/
and run `killall plasmashell; kstart5 plasmashell`to refresh the widget files.

**Comment by atul-g** [comment] 2022-07-05 17:09
@Tarballwalf @martinalex000 @j4nm4c - sorry for the delayed response! Was unable to find time due to college/job : D

@Tarballwalf & @martinalex000 - could you please share me the output of the following commands:
- `ls /sys/class/power_supply`
- `cat /sys/class/power_supply/BAT[num]/present` for each battery `[num]` present in laptop

Additionally, @Tarballwalf could you also share me the output of this command:
- `cat /sys/class/power_supply/BAT[num]/power_now`

Currently, in code, I did ensure to check if the `power_now` file exists and use that to fetch the power usage, so I'm not sure why it doesn't show anything in your case (by "doesn't show the wattage at all", did you mean it shows "0.0 W"?)

One of the main hurdles of developing this widget has been that my laptop was the only device I had for reference, coding and testing and therefore I could not take into account laptops with dual batteries or different files provided by kernel for reporting battery power consumption (like power_now). So, thanks a lot for reporting these issues here!

**Comment by Tarballwalf** [comment] 2022-07-06 01:23
![image](https://user-images.githubusercontent.com/56345519/177445484-fd526d21-1446-4913-8f44-42877078a913.png)

Regarding the second question,
![image](https://user-images.githubusercontent.com/56345519/177445830-30de95da-607a-4cea-a454-92afcd39ab09.png)

The plugin works, but only when BAT0 is actively in use. If BAT1 is used, it will just report as 0.

**Comment by atul-g** [comment] 2022-07-07 08:11
Thanks @Tarballwalf !

I have released [v0.2](https://store.kde.org/p/1466838/) and it should be able to support dual batteries. I have not been able to test them as I don't have a laptop with dual batteries. Would request you to try out the new version and let me know if you face any regressions or if the widget still doesn't work!

**Comment by j4nm4c** [comment] 2022-07-07 09:06
Everything works fine for me 
(this is my setup):
```
ls /sys/class/power_supply/ | grep BAT
BAT0
BAT1
                                                                                                                                                                       
cat /sys/class/power_supply/BAT*/power_now
0
9454000
```

**Comment by atul-g** [comment] 2022-07-09 05:47
Thank you for confirming @j4nm4c  ! Closing this issue in that case.

**Closed as completed by atul-g** 2022-07-09 05:47 UTC
